/**
 * そだてるアプリ 公式マイルストーン マスターデータ
 * WHO基準・小児科学・発達心理学をもとに設計
 *
 * スコープ: 0歳〜12歳（小学校卒業まで）
 *   Phase 1: 乳児期（0〜1歳）
 *   Phase 2: 幼児前期（1〜3歳）
 *   Phase 3: 幼児後期（3〜6歳）
 *   Phase 4: 学齢期（6〜12歳）
 *
 * 思春期以降（中学生以上）は別プロダクトとしてスコープ外。
 * 詳細は docs/product-vision.md ver.2 と docs/milestones-redesign.md を参照。
 *
 * ID体系（B案・連番再割当）:
 *   M-001〜M-016: Phase 1（16項目・既存）
 *   M-017〜M-027: Phase 2（11項目・既存10 + 2歳の誕生日 1項目を新規追加）
 *   M-028〜M-038: Phase 3（11項目・既存5 + 新規6項目）
 *   M-039〜M-056: Phase 4（18項目・既存8 + 新規10項目を拡張）
 *   合計56項目
 */

export type MilestoneData = {
  id: string;         // M-001 形式
  title: string;      // 日本語タイトル
  title_en: string;   // 英語タイトル
  category: string;   // カテゴリ（身体/言語/社会性/認知/人生節目）
  phase: number;      // 1〜4（思春期以降はスコープ外）
  age_hint: string;   // 目安年齢
  is_premium: boolean; // 無料版=false（後で有料版制御を入れる）
  evidence: "who" | "research" | "sodatelu"; // 根拠レベル（WHO基準/発達研究/sodatelu独自）
  description: string; // 補足説明文（親向け、1〜2行）
};

export const MILESTONES: MilestoneData[] = [
  // ============================================================
  // Phase 1 — 乳児期 0〜1歳（16項目）
  // ============================================================
  {
    id: "M-001",
    title: "初めての笑顔（社会的微笑）",
    title_en: "Social smile",
    category: "社会性",
    phase: 1,
    age_hint: "生後4〜8週",
    is_premium: false,
    evidence: "research",
    description: "あやしたときに笑う反応。反射的な微笑とは違い、社会的なつながりの第一歩",
  },
  {
    id: "M-002",
    title: "首すわり",
    title_en: "Head control",
    category: "身体",
    phase: 1,
    age_hint: "生後3〜4ヶ月",
    is_premium: false,
    evidence: "who",
    description: "腹ばいで頭を持ち上げられる状態。WHO Motor Development Studyの基本指標のひとつ",
  },
  {
    id: "M-003",
    title: "喃語（バブリング）開始",
    title_en: "Babbling onset",
    category: "言語",
    phase: 1,
    age_hint: "生後4〜6ヶ月",
    is_premium: false,
    evidence: "research",
    description: "「ばばば」「まままま」など音の繰り返し。言葉の土台となる発声練習が始まる時期",
  },
  {
    id: "M-004",
    title: "寝返り",
    title_en: "Rolling over",
    category: "身体",
    phase: 1,
    age_hint: "生後4〜6ヶ月",
    is_premium: false,
    evidence: "who",
    description: "仰向けからうつ伏せ、またはその逆に自力で体を回転させる。WHO運動発達指標のひとつ",
  },
  {
    id: "M-005",
    title: "お座り（支えなし）",
    title_en: "Sitting without support",
    category: "身体",
    phase: 1,
    age_hint: "生後6〜8ヶ月",
    is_premium: false,
    evidence: "who",
    description: "支えなしで安定して座れる。WHO Motor Studyの6指標のひとつ",
  },
  {
    id: "M-006",
    title: "離乳食開始",
    title_en: "Introduction of solid food",
    category: "身体",
    phase: 1,
    age_hint: "生後5〜6ヶ月",
    is_premium: false,
    evidence: "who",
    description: "WHOは生後6ヶ月からの補完食開始を推奨。母乳やミルクだけでは栄養が足りなくなる時期",
  },
  {
    id: "M-007",
    title: "第一乳歯の萌出",
    title_en: "First tooth eruption",
    category: "身体",
    phase: 1,
    age_hint: "生後6〜10ヶ月",
    is_premium: false,
    evidence: "research",
    description: "多くの場合、下の前歯から生え始める。生える時期には個人差が大きい",
  },
  {
    id: "M-008",
    title: "人見知り開始",
    title_en: "Stranger anxiety onset",
    category: "社会性",
    phase: 1,
    age_hint: "生後6〜9ヶ月",
    is_premium: false,
    evidence: "research",
    description: "親と他人を区別できるようになった証拠。愛着形成が順調に進んでいるサイン",
  },
  {
    id: "M-009",
    title: "ハイハイ開始",
    title_en: "Crawling onset",
    category: "身体",
    phase: 1,
    age_hint: "生後7〜10ヶ月",
    is_premium: false,
    evidence: "who",
    description: "手と膝を使って移動する。WHO Motor Studyの6指標のひとつ。しない子もいるが問題はない",
  },
  {
    id: "M-010",
    title: "つかまり立ち",
    title_en: "Standing with support",
    category: "身体",
    phase: 1,
    age_hint: "生後8〜10ヶ月",
    is_premium: false,
    evidence: "who",
    description: "家具などにつかまって立ち上がる。WHO Motor Studyの6指標のひとつで、歩行への重要なステップ",
  },
  {
    id: "M-011",
    title: "指差し（共同注意）",
    title_en: "Pointing / joint attention",
    category: "認知",
    phase: 1,
    age_hint: "生後9〜12ヶ月",
    is_premium: false,
    evidence: "research",
    description: "気になるものを指差して大人と共有する行動。発達の重要な指標として注目されている",
  },
  {
    id: "M-012",
    title: "初語（意味のある言葉）",
    title_en: "First word",
    category: "言語",
    phase: 1,
    age_hint: "生後10〜14ヶ月",
    is_premium: false,
    evidence: "research",
    description: "「ママ」「ワンワン」など意味を持った最初の言葉。言語発達研究で広く追跡される指標",
  },
  {
    id: "M-013",
    title: "一人立ち（支えなし）",
    title_en: "Standing alone",
    category: "身体",
    phase: 1,
    age_hint: "生後10〜13ヶ月",
    is_premium: false,
    evidence: "who",
    description: "何にもつかまらず数秒以上立てる。WHO Motor Studyの6指標のひとつ",
  },
  {
    id: "M-014",
    title: "独立歩行",
    title_en: "Independent walking",
    category: "身体",
    phase: 1,
    age_hint: "生後11〜15ヶ月",
    is_premium: false,
    evidence: "who",
    description: "世界中の研究で最もデータが豊富な発達指標。WHO中央値は生後354日",
  },
  {
    id: "M-015",
    title: "模倣行動（まねっこ）",
    title_en: "Imitation behavior",
    category: "認知",
    phase: 1,
    age_hint: "生後9〜12ヶ月",
    is_premium: false,
    evidence: "research",
    description: "大人の動作を見てまねをする。学習の基本であり、社会性の発達にもつながる行動",
  },
  {
    id: "M-016",
    title: "1歳の誕生日",
    title_en: "1st birthday",
    category: "人生節目",
    phase: 1,
    age_hint: "生後365日",
    is_premium: false,
    evidence: "sodatelu",
    description: "すべての子どもに共通する記念日。ここまでの成長を振り返る大切な節目",
  },

  // ============================================================
  // Phase 2 — 幼児前期 1〜3歳（11項目）
  // ============================================================
  {
    id: "M-017",
    title: "二語文の開始",
    title_en: "Two-word combinations",
    category: "言語",
    phase: 2,
    age_hint: "18〜24ヶ月",
    is_premium: false,
    evidence: "who",
    description: "「ママ きた」「わんわん いた」など2つの言葉をつなげて話す。言語爆発期の入り口",
  },
  {
    id: "M-018",
    title: "走る",
    title_en: "Running",
    category: "身体",
    phase: 2,
    age_hint: "18〜24ヶ月",
    is_premium: false,
    evidence: "who",
    description: "歩行が安定し、小走りからやがて本格的に走れるように。WHO運動発達の延長指標",
  },
  {
    id: "M-019",
    title: "排泄の自立（トイレ）",
    title_en: "Toilet training completion",
    category: "身体",
    phase: 2,
    age_hint: "2〜3歳",
    is_premium: false,
    evidence: "research",
    description: "膀胱と腸のコントロールが可能になる時期。完了の時期には文化差・個人差が大きい",
  },
  {
    id: "M-020",
    title: "自分で食事（スプーン）",
    title_en: "Self-feeding with utensil",
    category: "身体",
    phase: 2,
    age_hint: "18〜24ヶ月",
    is_premium: false,
    evidence: "research",
    description: "スプーンやフォークを使って自分で食べられるようになる。手先の発達と自立心の表れ",
  },
  {
    id: "M-021",
    title: "ごっこ遊びの開始",
    title_en: "Pretend play onset",
    category: "認知",
    phase: 2,
    age_hint: "18〜24ヶ月",
    is_premium: false,
    evidence: "research",
    description: "見立てや想像で遊べるようになる。ピアジェの象徴機能の発達として研究されている",
  },
  {
    id: "M-022",
    title: "自分の名前を言える",
    title_en: "States own name",
    category: "言語",
    phase: 2,
    age_hint: "24〜30ヶ月",
    is_premium: false,
    evidence: "research",
    description: "「ぼく○○」と名乗れるようになる。自己認識の発達を示す重要な言語的マイルストーン",
  },
  {
    id: "M-023",
    title: "階段を上る（交互に）",
    title_en: "Climbing stairs alternating feet",
    category: "身体",
    phase: 2,
    age_hint: "2〜3歳",
    is_premium: false,
    evidence: "research",
    description: "左右の足を交互に出して階段を上がれる。バランス感覚と筋力の発達を反映する指標",
  },
  {
    id: "M-024",
    title: "三語文以上",
    title_en: "Three-word sentences",
    category: "言語",
    phase: 2,
    age_hint: "24〜36ヶ月",
    is_premium: false,
    evidence: "research",
    description: "「パパ おしごと いった」など3語以上の文を組み立てられる。文法理解が進んでいる証拠",
  },
  {
    id: "M-025",
    title: "他の子どもへの関心・並行遊び",
    title_en: "Parallel play with peers",
    category: "社会性",
    phase: 2,
    age_hint: "2〜3歳",
    is_premium: false,
    evidence: "research",
    description: "同じ場所で隣り合って遊ぶが、まだ一緒には遊ばない段階。パーテンの遊び分類で定義される",
  },
  {
    id: "M-026",
    title: "自分で着替え（部分的）",
    title_en: "Partial self-dressing",
    category: "身体",
    phase: 2,
    age_hint: "2〜3歳",
    is_premium: false,
    evidence: "research",
    description: "靴を脱ぐ、ズボンを上げるなど一部の着替えを自分でやりたがる。自立心の芽生え",
  },
  {
    id: "M-027",
    title: "2歳の誕生日",
    title_en: "2nd birthday",
    category: "人生節目",
    phase: 2,
    age_hint: "生後2年",
    is_premium: false,
    evidence: "sodatelu",
    description: "言葉も歩みもぐっと広がる節目。1歳から2歳までの劇的な成長を振り返る記念日",
  },

  // ============================================================
  // Phase 3 — 幼児後期 3〜6歳（11項目）
  // 言語爆発・社会性の開花・認知の急発達期。sodateluのコア層
  // ============================================================
  {
    id: "M-028",
    title: "三輪車・ペダル漕ぎ",
    title_en: "Pedaling tricycle",
    category: "身体",
    phase: 3,
    age_hint: "3〜4歳",
    is_premium: false,
    evidence: "research",
    description: "足でペダルを回して前に進む動作。左右の足の協調運動ができるようになった証",
  },
  {
    id: "M-029",
    title: "ひとりで用を足せる",
    title_en: "Independent toileting",
    category: "身体",
    phase: 3,
    age_hint: "3〜5歳",
    is_premium: false,
    evidence: "research",
    description: "トイレに行く・拭く・流す・手を洗うまでを一人で完結できる。日常的な自立の大きな一歩",
  },
  {
    id: "M-030",
    title: "友達の名前を覚える・友達ができる",
    title_en: "Develops first friendships",
    category: "社会性",
    phase: 3,
    age_hint: "3〜5歳",
    is_premium: false,
    evidence: "research",
    description: "特定の子と遊びたがるようになる。対人関係の選好が生まれ、社会性が深まる時期",
  },
  {
    id: "M-031",
    title: "心の理論の確立",
    title_en: "Theory of mind",
    category: "認知",
    phase: 3,
    age_hint: "4〜5歳",
    is_premium: false,
    evidence: "research",
    description: "他者の気持ちや考えが自分とは違うと理解できる能力。誤信念課題の研究で知られる",
  },
  {
    id: "M-032",
    title: "はじめての習い事",
    title_en: "First extracurricular activity",
    category: "人生節目",
    phase: 3,
    age_hint: "3〜8歳",
    is_premium: false,
    evidence: "sodatelu",
    description: "ピアノ、水泳、サッカーなど。家庭と学校以外の「自分の世界」ができる体験",
  },
  {
    id: "M-033",
    title: "数の概念（1〜10を数えられる）",
    title_en: "Counting 1 to 10",
    category: "認知",
    phase: 3,
    age_hint: "3〜5歳",
    is_premium: false,
    evidence: "research",
    description: "順番に数を唱えるだけでなく、ものの数として理解できる。就学前の認知発達の重要な指標",
  },
  {
    id: "M-034",
    title: "色・形の名前を言える",
    title_en: "Names colors and shapes",
    category: "認知",
    phase: 3,
    age_hint: "3〜4歳",
    is_premium: false,
    evidence: "research",
    description: "赤・青・丸・三角などを言葉で区別できる。分類能力の発達を示し、就学準備の基礎となる",
  },
  {
    id: "M-035",
    title: "順番を待てる（ルールに従う）",
    title_en: "Takes turns and follows rules",
    category: "社会性",
    phase: 3,
    age_hint: "3〜5歳",
    is_premium: false,
    evidence: "research",
    description: "順番待ちや簡単なルールが守れるようになる。自己調整能力と集団生活への適応の現れ",
  },
  {
    id: "M-036",
    title: "ハサミ・クレヨンを使える",
    title_en: "Uses scissors and crayons",
    category: "身体",
    phase: 3,
    age_hint: "3〜5歳",
    is_premium: false,
    evidence: "research",
    description: "線に沿って切る、丸を描くなど道具を使った微細運動。手先の発達指標として重要",
  },
  {
    id: "M-037",
    title: "「なんで？」の質問期",
    title_en: "Why-question phase",
    category: "言語",
    phase: 3,
    age_hint: "3〜4歳",
    is_premium: false,
    evidence: "sodatelu",
    description: "「どうして？」「なんで？」と何度も尋ねる時期。知的好奇心の爆発的な広がり",
  },
  {
    id: "M-038",
    title: "3歳の誕生日",
    title_en: "3rd birthday",
    category: "人生節目",
    phase: 3,
    age_hint: "生後3年",
    is_premium: false,
    evidence: "sodatelu",
    description: "幼児期の大きな節目。保育園や幼稚園に通い始める頃と重なることも多い記念日",
  },

  // ============================================================
  // Phase 4 — 学齢期 6〜12歳（18項目）
  // 小学校の6年間。ここまでがsodateluのスコープ
  // 既存8項目 + 新規10項目（認知5・身体2・社会性3）で7年間を厚く支える
  // ============================================================
  {
    id: "M-039",
    title: "補助輪なし自転車",
    title_en: "Riding bicycle without training wheels",
    category: "身体",
    phase: 4,
    age_hint: "4〜7歳",
    is_premium: false,
    evidence: "sodatelu",
    description: "文化によって差があるが、達成感と自信の大きな節目。親子の思い出にもなりやすい",
  },
  {
    id: "M-040",
    title: "ひらがな読み書き",
    title_en: "Basic literacy (native script)",
    category: "認知",
    phase: 4,
    age_hint: "5〜7歳",
    is_premium: false,
    evidence: "sodatelu",
    description: "日本の子どもにとっての識字の入り口。手紙を書いたり絵本を自分で読む楽しさが広がる",
  },
  {
    id: "M-041",
    title: "小学校入学",
    title_en: "Elementary school enrollment",
    category: "人生節目",
    phase: 4,
    age_hint: "6〜7歳",
    is_premium: false,
    evidence: "sodatelu",
    description: "学びの場が家庭から学校へ広がる大きな転換点。新しい人間関係と生活リズムが始まる",
  },
  {
    id: "M-042",
    title: "泳げるようになる（25m）",
    title_en: "Swimming (25m)",
    category: "身体",
    phase: 4,
    age_hint: "6〜10歳",
    is_premium: false,
    evidence: "sodatelu",
    description: "日本では小学校の水泳授業で目標にされることが多い。水の安全教育としても重要",
  },
  {
    id: "M-043",
    title: "お手伝いができる",
    title_en: "Helping with household tasks",
    category: "社会性",
    phase: 4,
    age_hint: "5〜8歳",
    is_premium: false,
    evidence: "research",
    description: "食器を運ぶ、洗濯物をたたむなど家事に参加する。責任感と家族への貢献意識が育つ",
  },
  {
    id: "M-044",
    title: "一人でのお使い",
    title_en: "First solo errand",
    category: "社会性",
    phase: 4,
    age_hint: "6〜10歳",
    is_premium: false,
    evidence: "sodatelu",
    description: "日本では「はじめてのおつかい」として親しまれている文化的な成長体験",
  },
  {
    id: "M-045",
    title: "論理的思考・因果関係の理解",
    title_en: "Logical / causal reasoning",
    category: "認知",
    phase: 4,
    age_hint: "7〜10歳",
    is_premium: false,
    evidence: "research",
    description: "「こうしたからこうなった」と筋道を立てて考えられる。ピアジェの具体的操作期に対応",
  },
  {
    id: "M-046",
    title: "小学校卒業",
    title_en: "Elementary school graduation",
    category: "人生節目",
    phase: 4,
    age_hint: "12歳",
    is_premium: false,
    evidence: "sodatelu",
    description: "sodateluが見守る12年間の最終節目。ここまでの成長を一冊のアルバムとして振り返る",
  },
  // ----- 認知系（5項目）-----
  {
    id: "M-047",
    title: "ひらがな・カタカナの読み書き",
    title_en: "Hiragana and Katakana literacy",
    category: "認知",
    phase: 4,
    age_hint: "6〜7歳",
    is_premium: false,
    evidence: "research",
    description: "学齢期に入って文字の読み書きが本格的に始まる時期。多くの子が小学1年生のあいだに身につけていく [出典: 文部科学省 小学校学習指導要領 国語編]",
  },
  {
    id: "M-048",
    title: "簡単な足し算・引き算",
    title_en: "Basic addition and subtraction",
    category: "認知",
    phase: 4,
    age_hint: "6〜7歳",
    is_premium: false,
    evidence: "research",
    description: "数を量として扱い、たし算・ひき算ができるようになる時期。学校の授業や生活のなかで少しずつ広がる [出典: 文部科学省 小学校学習指導要領 算数編 / MSDマニュアル 学齢期の発達]",
  },
  {
    id: "M-049",
    title: "時計を読む（短針・長針）",
    title_en: "Reading an analog clock",
    category: "認知",
    phase: 4,
    age_hint: "7〜8歳",
    is_premium: false,
    evidence: "research",
    description: "短い針と長い針の意味がわかり、自分で時刻を読めるように。時間の感覚が育ち、生活の見通しが立てやすくなる [出典: Bright Futures (AAP) / 文部科学省 小学校学習指導要領]",
  },
  {
    id: "M-050",
    title: "お金の計算（買い物）",
    title_en: "Money math and shopping",
    category: "認知",
    phase: 4,
    age_hint: "7〜9歳",
    is_premium: false,
    evidence: "research",
    description: "硬貨やお札の組み合わせがわかり、おつりの計算ができるように。実生活と算数がつながっていく時期 [出典: Bright Futures (AAP) Middle Childhood]",
  },
  {
    id: "M-051",
    title: "読書を楽しむ・物語を最後まで読める",
    title_en: "Reading for pleasure",
    category: "認知",
    phase: 4,
    age_hint: "8〜10歳",
    is_premium: false,
    evidence: "research",
    description: "絵本から児童書へと、文字の世界が広がっていく時期。好きなジャンルや作家ができることもある [出典: Bright Futures (AAP) / 文部科学省 学習指導要領 国語編]",
  },
  // ----- 身体系（2項目）-----
  {
    id: "M-052",
    title: "交通ルールを守って外を歩ける",
    title_en: "Walking safely with traffic rules",
    category: "身体",
    phase: 4,
    age_hint: "6〜8歳",
    is_premium: false,
    evidence: "research",
    description: "信号や横断歩道のルールを理解して、自分で気をつけながら歩けるようになる。通学の自立につながる大切なステップ [出典: 警察庁 交通安全教育指針 / 文部科学省 安全教育]",
  },
  {
    id: "M-053",
    title: "二次性徴の前兆",
    title_en: "Onset of puberty signs",
    category: "身体",
    phase: 4,
    age_hint: "女子8〜10歳・男子9〜12歳",
    is_premium: false,
    evidence: "research",
    description: "身長の伸びや体つきの変化など、思春期に向けた体のサインがあらわれ始める時期。始まる時期や進み方には個人差がとても大きい。気になることがあれば、かかりつけ医に相談してみると安心 [出典: Norton Children's / AAP Bright Futures]",
  },
  // ----- 社会性系（3項目）-----
  {
    id: "M-054",
    title: "仲の良い友達ができる",
    title_en: "Forms close friendships",
    category: "社会性",
    phase: 4,
    age_hint: "6〜8歳",
    is_premium: false,
    evidence: "research",
    description: "「いつも一緒に遊ぶ子」「お話しが合う子」など、特定の友達との関係が深まっていく時期。家族の外に自分の居場所が広がっていく [出典: Norton Children's / Bright Futures]",
  },
  {
    id: "M-055",
    title: "委員会・係活動に取り組む",
    title_en: "Participates in school committees",
    category: "社会性",
    phase: 4,
    age_hint: "9〜12歳",
    is_premium: false,
    evidence: "research",
    description: "学校で役割を任されて、責任感や協力する力が育つ時期。家のなかでは見えなかった一面が出てくることもある [出典: 文部科学省 小学校学習指導要領 特別活動編]",
  },
  {
    id: "M-056",
    title: "親友・グループ意識の芽生え",
    title_en: "Best friend and group identity",
    category: "社会性",
    phase: 4,
    age_hint: "9〜12歳",
    is_premium: false,
    evidence: "research",
    description: "「親友」と呼べる存在ができたり、仲間グループのつながりを大切にするようになる時期。子ども自身の世界がぐっと広がっていく [出典: Norton Children's / AAP Middle Childhood]",
  },
];
